package intelligence

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/ashwingopalsamy/agentic-go/internal/workspace"
)

func TestExportedInventory(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sample.go")
	content := "// Code generated by fixture. DO NOT EDIT.\n//go:build linux\npackage sample\n\nimport \"fmt\"\n\nconst Answer = 42\ntype Widget struct{}\nfunc NewWidget() *Widget { fmt.Println(Answer); return &Widget{} }\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	got, generated, constrained, err := exportedInventory(context.Background(), dir, []string{"sample.go"})
	if err != nil {
		t.Fatal(err)
	}
	if !generated || !constrained {
		t.Fatalf("flags = generated %v constrained %v", generated, constrained)
	}
	want := []string{"const Answer", "func NewWidget() *Widget", "type Widget struct{}"}
	if len(got) != len(want) {
		t.Fatalf("exported = %#v, want %#v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("exported[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

func TestInventoryGuidanceIsRelativeAndHasDigest(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "AGENTS.md"), []byte("guidance\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/fixture\n\ngo 1.25\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(filepath.Join(root, "nested"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "nested", "CLAUDE.md"), []byte("more\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	ws, err := workspace.Open(t.Context(), root)
	if err != nil {
		t.Fatal(err)
	}
	refs, err := inventoryGuidance(context.Background(), ws)
	if err != nil {
		t.Fatal(err)
	}
	if len(refs) != 2 || refs[0].File != "AGENTS.md" || refs[1].File != "nested/CLAUDE.md" {
		t.Fatalf("refs = %#v", refs)
	}
	if refs[0].Digest == "" || len(refs[0].Digest) != 64 {
		t.Fatalf("digest = %q", refs[0].Digest)
	}
}

func TestExportedInventoryStopsOnCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, _, _, err := exportedInventory(ctx, t.TempDir(), []string{"missing.go"}); !errors.Is(err, context.Canceled) {
		t.Fatalf("exportedInventory() error = %v, want context.Canceled", err)
	}
}
