package intelligence

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func (p *fakeSemanticProvider) Refactor(_ context.Context, _ SnapshotRef, _ semanticRefactorRequest) ([]semanticFileEdits, error) {
	return append([]semanticFileEdits(nil), p.refactorEdits...), p.refactorErr
}

func TestCoreRefactorPreviewIsDeterministicAndNonMutating(t *testing.T) {
	root := snapshotRepository(t)
	before := "package fixture\n\nvar Value = 1\n"
	writeSnapshotFile(t, root, "main.go", before)
	core := newTestCore(t, newTestSnapshotter(t, root), &fakeSemanticReader{})
	core.semantic.(*fakeSemanticProvider).refactorEdits = []semanticFileEdits{{
		Path: "main.go", Edits: []semanticTextEdit{{Start: 21, End: 26, NewText: "Renamed"}},
	}}
	snapshot, err := core.capture(context.Background(), "", "./...", "")
	if err != nil {
		t.Fatal(err)
	}
	ref, err := encodeSymbolRef(symbolIdentity{
		SnapshotID: snapshot.ID, Path: "main.go", Scope: "./...",
		Position: Position{Line: 2, Character: 4}, Kind: "go.variable", Package: "fixture", Qualified: "fixture.Value",
	})
	if err != nil {
		t.Fatal(err)
	}
	request := RefactorRequest{
		Operation: RefactorRename, Ref: ref, NewName: "Renamed", ExpectedSnapshotID: snapshot.ID,
	}
	first, err := core.Refactor(context.Background(), request)
	if err != nil {
		t.Fatal(err)
	}
	second, err := core.Refactor(context.Background(), request)
	if err != nil {
		t.Fatal(err)
	}
	if first.PlanID == "" || first.PlanID != second.PlanID || first.Applied || len(first.Preimages) != 1 {
		t.Fatalf("preview = %#v, repeated = %#v", first, second)
	}
	if first.Preimages[0].Path != "main.go" || first.Preimages[0].Digest != digestBytes([]byte(before)) {
		t.Fatalf("preimages = %#v", first.Preimages)
	}
	if !strings.Contains(first.Diff, "-var Value = 1") || !strings.Contains(first.Diff, "+var Renamed = 1") {
		t.Fatalf("diff = %q", first.Diff)
	}
	contents, err := os.ReadFile(filepath.Join(root, "main.go"))
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != before {
		t.Fatalf("preview mutated file to %q", contents)
	}
}

func TestCoreRefactorApplyWritesExactPlanAndClearsJournal(t *testing.T) {
	root := snapshotRepository(t)
	writeSnapshotFile(t, root, "main.go", "package fixture\n\nvar Value=1\n")
	core := newTestCore(t, newTestSnapshotter(t, root), &fakeSemanticReader{})
	core.semantic.(*fakeSemanticProvider).refactorEdits = []semanticFileEdits{{
		Path: "main.go", Edits: []semanticTextEdit{{Start: 26, End: 26, NewText: " "}},
	}}
	snapshot, err := core.capture(context.Background(), "", "./...", "")
	if err != nil {
		t.Fatal(err)
	}
	preview, err := core.Refactor(context.Background(), RefactorRequest{
		Operation: RefactorFormat, Files: []string{"main.go"}, ExpectedSnapshotID: snapshot.ID,
	})
	if err != nil {
		t.Fatal(err)
	}
	applied, err := core.Refactor(context.Background(), RefactorRequest{
		PlanID: preview.PlanID, ExpectedSnapshotID: snapshot.ID, Apply: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !applied.Applied || applied.PlanID != preview.PlanID || applied.Snapshot.ID == snapshot.ID {
		t.Fatalf("applied = %#v", applied)
	}
	contents, err := os.ReadFile(filepath.Join(root, "main.go"))
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != "package fixture\n\nvar Value =1\n" {
		t.Fatalf("main.go = %q", contents)
	}
	if _, err := core.refactors.pending(context.Background(), snapshot.RepositoryID); !errors.Is(err, errRefactorRecoveryNotFound) {
		t.Fatalf("recovery journal remains: %v", err)
	}
}

func TestCoreRefactorRejectsStaleApplyAndGeneratedSource(t *testing.T) {
	t.Run("stale apply", func(t *testing.T) {
		root := snapshotRepository(t)
		writeSnapshotFile(t, root, "main.go", "package fixture\n\nvar Value=1\n")
		core := newTestCore(t, newTestSnapshotter(t, root), &fakeSemanticReader{})
		core.semantic.(*fakeSemanticProvider).refactorEdits = []semanticFileEdits{{
			Path: "main.go", Edits: []semanticTextEdit{{Start: 26, End: 26, NewText: " "}},
		}}
		snapshot, err := core.capture(context.Background(), "", "./...", "")
		if err != nil {
			t.Fatal(err)
		}
		preview, err := core.Refactor(context.Background(), RefactorRequest{
			Operation: RefactorFormat, Files: []string{"main.go"}, ExpectedSnapshotID: snapshot.ID,
		})
		if err != nil {
			t.Fatal(err)
		}
		writeSnapshotFile(t, root, "main.go", "package fixture\n\nvar UserEdit=1\n")
		if _, err := core.Refactor(context.Background(), RefactorRequest{
			PlanID: preview.PlanID, ExpectedSnapshotID: snapshot.ID, Apply: true,
		}); !errors.Is(err, ErrSnapshotChanged) {
			t.Fatalf("apply error = %v, want ErrSnapshotChanged", err)
		}
	})

	t.Run("generated source", func(t *testing.T) {
		root := snapshotRepository(t)
		writeSnapshotFile(t, root, "generated.go", "// Code generated by fixture. DO NOT EDIT.\npackage fixture\n")
		core := newTestCore(t, newTestSnapshotter(t, root), &fakeSemanticReader{})
		core.semantic.(*fakeSemanticProvider).refactorEdits = []semanticFileEdits{{
			Path: "generated.go", Edits: []semanticTextEdit{{Start: 47, End: 54, NewText: "changed"}},
		}}
		snapshot, err := core.capture(context.Background(), "", "./...", "")
		if err != nil {
			t.Fatal(err)
		}
		if _, err := core.Refactor(context.Background(), RefactorRequest{
			Operation: RefactorFormat, Files: []string{"generated.go"}, ExpectedSnapshotID: snapshot.ID,
		}); err == nil || !strings.Contains(err.Error(), "generated") {
			t.Fatalf("preview error = %v", err)
		}
	})
}

func TestCoreRefactorRollsBackPartialMultiFileApply(t *testing.T) {
	root := snapshotRepository(t)
	writeSnapshotFile(t, root, "a.go", "package fixture\nvar A=1\n")
	writeSnapshotFile(t, root, "b.go", "package fixture\nvar B=2\n")
	core := newTestCore(t, newTestSnapshotter(t, root), &fakeSemanticReader{})
	core.semantic.(*fakeSemanticProvider).refactorEdits = []semanticFileEdits{
		{Path: "a.go", Edits: []semanticTextEdit{{Start: 21, End: 21, NewText: " "}}},
		{Path: "b.go", Edits: []semanticTextEdit{{Start: 21, End: 21, NewText: " "}}},
	}
	snapshot, err := core.capture(context.Background(), "", "./...", "")
	if err != nil {
		t.Fatal(err)
	}
	preview, err := core.Refactor(context.Background(), RefactorRequest{
		Operation: RefactorFormat, Files: []string{"a.go", "b.go"}, ExpectedSnapshotID: snapshot.ID,
	})
	if err != nil {
		t.Fatal(err)
	}
	writes := 0
	core.refactorWrite = func(path string, contents []byte, mode os.FileMode) error {
		writes++
		if writes == 2 {
			return errors.New("injected write failure")
		}
		return atomicReplace(path, contents, mode)
	}
	if _, err := core.Refactor(context.Background(), RefactorRequest{
		PlanID: preview.PlanID, ExpectedSnapshotID: snapshot.ID, Apply: true,
	}); err == nil || !strings.Contains(err.Error(), "injected write failure") {
		t.Fatalf("apply error = %v", err)
	}
	for path, want := range map[string]string{
		"a.go": "package fixture\nvar A=1\n",
		"b.go": "package fixture\nvar B=2\n",
	} {
		contents, readErr := os.ReadFile(filepath.Join(root, path))
		if readErr != nil || string(contents) != want {
			t.Fatalf("%s = %q, %v", path, contents, readErr)
		}
	}
	if _, err := core.refactors.pending(context.Background(), snapshot.RepositoryID); !errors.Is(err, errRefactorRecoveryNotFound) {
		t.Fatalf("journal remains after rollback: %v", err)
	}
}
