package changeimpact

import (
	"reflect"
	"testing"

	"github.com/agentic-mcps/go/internal/verification"
)

func TestAssessRiskActivatesSourceGroundedLenses(t *testing.T) {
	content := []byte(`package sample

import (
	"errors"
	"fmt"
	"net/http"
)

func Exported(err error) string {
	go func() {}()
	http.HandleFunc("/", nil)
	for range []int{1} {}
	if err != nil { _ = errors.Is(err, err) }
	return fmt.Sprintf("%v", err)
}
`)
	analysis := verification.ChangeAnalysis{
		Change: verification.Change{
			Files:        []verification.ChangedFile{{Path: "sample.go", Change: verification.ChangeModified, CurrentRanges: []verification.LineRange{{Start: 9, End: 15}}}},
			Declarations: []verification.ChangedDeclaration{{Kind: "function", Package: "example.test/sample", Name: "Exported", Change: verification.ChangeModified, CurrentLocation: &verification.Location{File: "sample.go", Line: 9}}},
		},
		Files: []verification.SourceFile{{
			Change:         verification.ChangedFile{Path: "sample.go", Change: verification.ChangeModified, CurrentRanges: []verification.LineRange{{Start: 9, End: 15}}},
			CurrentContent: content,
		}},
	}

	risks, uncertainties, err := assessRisk(analysis)
	if err != nil {
		t.Fatal(err)
	}
	codes := make([]string, 0, len(risks))
	for _, risk := range risks {
		codes = append(codes, risk.Code)
	}
	want := []string{"error_flow_change", "exported_api_change", "http_boundary_change", "performance_sensitive_change", "synchronization_change"}
	if !reflect.DeepEqual(codes, want) {
		t.Fatalf("risk codes = %v, want %v", codes, want)
	}
	if len(uncertainties) != 1 || uncertainties[0].Code != "external_consumers" {
		t.Fatalf("uncertainties = %#v, want external_consumers", uncertainties)
	}
}

func TestAssessRiskIgnoresLexicalNearMisses(t *testing.T) {
	content := []byte(`package sample

// go routine, HTTP, crypto, database, Lock, and panic are prose.
func local() string { return "fmt.Sprintf and errors.New are strings" }
`)
	analysis := verification.ChangeAnalysis{
		Change: verification.Change{Files: []verification.ChangedFile{{Path: "sample.go", Change: verification.ChangeModified, CurrentRanges: []verification.LineRange{{Start: 3, End: 4}}}}},
		Files: []verification.SourceFile{{
			Change:         verification.ChangedFile{Path: "sample.go", Change: verification.ChangeModified, CurrentRanges: []verification.LineRange{{Start: 3, End: 4}}},
			CurrentContent: content,
		}},
	}
	risks, uncertainties, err := assessRisk(analysis)
	if err != nil {
		t.Fatal(err)
	}
	if len(risks) != 0 || len(uncertainties) != 0 {
		t.Fatalf("near miss produced risks=%#v uncertainties=%#v", risks, uncertainties)
	}
}

func TestAssessRiskDisclosesMetadataGeneratedBuildAndCgoLimits(t *testing.T) {
	analysis := verification.ChangeAnalysis{
		Change: verification.Change{Files: []verification.ChangedFile{
			{Path: "go.mod", Change: verification.ChangeModified, CurrentRanges: []verification.LineRange{{Start: 1, End: 1}}},
			{Path: "generated.go", Change: verification.ChangeModified, CurrentRanges: []verification.LineRange{{Start: 1, End: 4}}},
		}},
		Files: []verification.SourceFile{{
			Change:         verification.ChangedFile{Path: "generated.go", Change: verification.ChangeModified, CurrentRanges: []verification.LineRange{{Start: 1, End: 4}}},
			CurrentContent: []byte("// Code generated by fixture. DO NOT EDIT.\n//go:build linux\npackage sample\n"),
		}},
		Packages: []verification.ExecutionTarget{{ID: "example.test/sample", Distance: 0, Cgo: true, BuildConstrained: true}},
	}
	risks, uncertainties, err := assessRisk(analysis)
	if err != nil {
		t.Fatal(err)
	}
	if len(risks) != 1 || risks[0].Code != "module_graph_change" {
		t.Fatalf("risks = %#v, want module_graph_change", risks)
	}
	codes := make([]string, 0, len(uncertainties))
	for _, uncertainty := range uncertainties {
		codes = append(codes, uncertainty.Code)
	}
	want := []string{"active_build_constraints", "cgo", "generated_code"}
	if !reflect.DeepEqual(codes, want) {
		t.Fatalf("uncertainty codes = %v, want %v", codes, want)
	}
}
