import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'agentic-action-'));
const report = path.join(dir, 'report.json');
const output = path.join(dir, 'output');
const summary = path.join(dir, 'summary');
fs.writeFileSync(report, JSON.stringify({ result: { status: 'findings', summary: 'review required' }, change: { files: [{}], files_total: 4, files_truncated: true, declarations: [{}], declarations_total: 3, declarations_truncated: true }, impact: { packages: [{ distance: 0 }, { distance: 1 }], packages_total: 4, packages_truncated: true }, evidence: [{ kind: 'go.test', status: 'passed' }], findings: [{ severity: 'error', message: 'bad%, change\nnow', location: { file: 'x,go', line: 4 } }, { severity: 'info', message: 'note' }], findings_total: 5, findings_truncated: true, risks: [], uncertainties: [] }));
const env = { ...process.env, GITHUB_OUTPUT: output, GITHUB_STEP_SUMMARY: summary };
const adapter = fileURLToPath(new URL('./action-report.mjs', import.meta.url));
let run = spawnSync(process.execPath, [adapter, report, '1', 'false'], { env, encoding: 'utf8' });
assert.equal(run.status, 0);
assert.match(fs.readFileSync(output, 'utf8'), /status=findings/);
assert.match(fs.readFileSync(summary, 'utf8'), /Change: 4 \(1 shown\) files, 3 \(1 shown\) declarations/);
assert.match(fs.readFileSync(summary, 'utf8'), /Findings: 5 \(2 shown\)/);
assert.match(fs.readFileSync(summary, 'utf8'), /Impact: 4 packages \(2 shown; visible: 1 direct, 1 reverse-dependent\)/);
assert.match(run.stdout, /::error,file=x%2Cgo,line=4::bad%25, change%0Anow/);
assert.match(run.stdout, /::notice::note/);
run = spawnSync(process.execPath, [adapter, report, '1', 'true'], { env, encoding: 'utf8' });
assert.equal(run.status, 1);
const fallbackReport = path.join(dir, 'fallback-report.json');
fs.writeFileSync(fallbackReport, JSON.stringify({ result: { status: 'pass' }, change: { files: [{}, {}], declarations: [{}] }, impact: { packages: [{ distance: 0 }, { distance: 1 }] }, findings: [{}] }));
run = spawnSync(process.execPath, [adapter, fallbackReport, '0', 'false'], { env, encoding: 'utf8' });
assert.equal(run.status, 0);
assert.match(fs.readFileSync(summary, 'utf8'), /Change: 2 files, 1 declarations/);
assert.match(fs.readFileSync(summary, 'utf8'), /Findings: 1/);
assert.match(fs.readFileSync(summary, 'utf8'), /Impact: 1 direct, 1 reverse-dependent packages/);
run = spawnSync(process.execPath, [adapter, report, '0', 'false'], { env, encoding: 'utf8' });
assert.equal(run.status, 3);
run = spawnSync(process.execPath, [adapter, report, '1', 'maybe'], { env, encoding: 'utf8' });
assert.equal(run.status, 3);
const invalid = path.join(dir, 'invalid.json'); fs.writeFileSync(invalid, '{');
run = spawnSync(process.execPath, [adapter, invalid, '0', 'false'], { env, encoding: 'utf8' });
assert.equal(run.status, 3);
console.log('action report adapter tests passed');
