import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'agentic-action-'));
const report = path.join(dir, 'report.json');
const output = path.join(dir, 'output');
const summary = path.join(dir, 'summary');
fs.writeFileSync(report, JSON.stringify({ result: { status: 'findings', summary: 'review required' }, change: { files: [{}], declarations: [{}] }, impact: { packages: [{ distance: 0 }, { distance: 1 }] }, evidence: [{ kind: 'go.test', status: 'passed' }], findings: [{ severity: 'error', message: 'bad%, change\nnow', location: { file: 'x,go', line: 4 } }, { severity: 'info', message: 'note' }], risks: [], uncertainties: [] }));
const env = { ...process.env, GITHUB_OUTPUT: output, GITHUB_STEP_SUMMARY: summary };
const adapter = fileURLToPath(new URL('./action-report.mjs', import.meta.url));
let run = spawnSync(process.execPath, [adapter, report, '1', 'false'], { env, encoding: 'utf8' });
assert.equal(run.status, 0);
assert.match(fs.readFileSync(output, 'utf8'), /status=findings/);
assert.match(fs.readFileSync(summary, 'utf8'), /Change: 1 files/);
assert.match(fs.readFileSync(summary, 'utf8'), /Impact: 1 direct, 1 reverse-dependent packages/);
assert.match(run.stdout, /::error,file=x%2Cgo,line=4::bad%25, change%0Anow/);
assert.match(run.stdout, /::notice::note/);
run = spawnSync(process.execPath, [adapter, report, '1', 'true'], { env, encoding: 'utf8' });
assert.equal(run.status, 1);
run = spawnSync(process.execPath, [adapter, report, '0', 'false'], { env, encoding: 'utf8' });
assert.equal(run.status, 3);
run = spawnSync(process.execPath, [adapter, report, '1', 'maybe'], { env, encoding: 'utf8' });
assert.equal(run.status, 3);
const invalid = path.join(dir, 'invalid.json'); fs.writeFileSync(invalid, '{');
run = spawnSync(process.execPath, [adapter, invalid, '0', 'false'], { env, encoding: 'utf8' });
assert.equal(run.status, 3);
console.log('action report adapter tests passed');
